### ISSUE TITLE
Parsing NCI data packet fails due to bytes being over flowed

### ISSUE THREAD

**Issue by nk521** [VivoKey/nfc-snoop-dogg#1]
Particular line I encountered this on -> https://github.com/VivoKey/nfc-snoop-dogg/blob/d6d177749c98ff818b68f042c11d558930680428/app/src/main/java/com/vivokey/nfcsnoopdecoder/NCIDecoder.java#L167

One of the packet sent has `payloadLength` to be 255. As `payloadLength` is a `byte`, this will lead to that variable be -1 instead of 255 which will then yield an error in `copyRange` function.

There are other places where similar stuff can happen.

A quick solution can be to just change the type of `payloadLength` to an Int and as an extra safeguard, bitwise and it with 0xFF.

**Comment by drewbug** [comment]
Thank you!
